# The data the attacker reads.
#
# Everything in here is synthetic, and it has to look like it isn't. The object
# keys go on screen during the demo -- an analyst reconstructing "what was taken"
# reads them aloud -- so dated, plausibly-named monthly exports are what make that
# beat land. `test1.csv` would not.
#
# The contents are equally deliberate: invented vendor names, round-ish numbers,
# nothing resembling a real person or a real company's finances. The read-only
# role cannot read these objects at all, so nobody in the room will ever see the
# contents -- but somebody with account access will, and this is a demo account
# that gets screen-shared.

locals {
  # A local rather than a resource attribute, for the reason quiv-iac's
  # object-store module gives: it is known at plan time, which is what lets the
  # IAM policies in other modules be asserted in CI rather than at apply.
  bucket_name = var.unique_suffix ? "${var.bucket_name}-${var.account_id}" : var.bucket_name
  bucket_arn  = "arn:aws:s3:::${local.bucket_name}"

  # Twelve months of exports, oldest first. Generated rather than written out so
  # that adding a year is a one-line change and the keys cannot drift out of
  # sequence.
  export_months = [
    "2025-09", "2025-10", "2025-11", "2025-12",
    "2026-01", "2026-02", "2026-03", "2026-04",
    "2026-05", "2026-06", "2026-07", "2026-08",
  ]

  exports = {
    for month in local.export_months :
    "exports/${substr(month, 0, 4)}/${substr(month, 5, 2)}/cost-allocation-${month}.csv" => month
  }
}

resource "aws_s3_bucket" "exports" {
  bucket = local.bucket_name

  # Unlike quiv-iac's object store, this one is meant to be destroyable: teardown
  # has to be able to return the account to baseline unattended, and everything in
  # here is regenerated by the next apply.
  force_destroy = true

  tags = merge(var.tags, { Name = local.bucket_name })
}

resource "aws_s3_bucket_public_access_block" "exports" {
  bucket = aws_s3_bucket.exports.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "exports" {
  bucket = aws_s3_bucket.exports.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# The bucket is not public and never should be, but the demo puts its policy on
# screen during blast-radius analysis -- so it carries the control an auditor
# would expect to find rather than an empty policy that invites the question.
resource "aws_s3_bucket_policy" "exports" {
  bucket = aws_s3_bucket.exports.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "DenyInsecureTransport"
      Effect    = "Deny"
      Principal = "*"
      Action    = "s3:*"
      Resource  = [local.bucket_arn, "${local.bucket_arn}/*"]
      Condition = {
        Bool = { "aws:SecureTransport" = "false" }
      }
    }]
  })

  depends_on = [aws_s3_bucket_public_access_block.exports]
}

# Synthetic content, written inline.
#
# `content` rather than a file on disk: twelve near-identical CSVs in the
# repository would be twelve files nobody reads and one more thing to keep in step
# with the key naming above.
resource "aws_s3_object" "exports" {
  for_each = local.exports

  bucket       = aws_s3_bucket.exports.id
  key          = each.key
  content_type = "text/csv"

  content = <<-CSV
    cost_center,vendor,service,month,amount_usd
    CC-1042,Northwind Logistics,freight,${each.value},18422.50
    CC-1042,Contoso Cloud,compute,${each.value},9310.75
    CC-2117,Fabrikam Supply,materials,${each.value},44190.00
    CC-2117,Contoso Cloud,storage,${each.value},2841.20
    CC-3305,Tailspin Travel,travel,${each.value},7655.90
    CC-3305,Adventure Works,catering,${each.value},1204.35
  CSV

  tags = merge(var.tags, { Name = each.key })
}
