mock_provider "aws" {}

variables {
  account_id = "431662316594"
}

run "the_bucket_name_does_not_announce_itself_as_a_fixture" {
  command = plan

  assert {
    condition     = !can(regex("(?i)serverless|demo|test|example", var.bucket_name))
    error_message = "An analyst reads this bucket name on screen while reconstructing what was taken; a name containing 'demo' tells them they are looking at a fixture."
  }
}

run "there_is_enough_data_to_reconstruct_a_pattern" {
  command = plan

  assert {
    condition     = length(local.exports) >= 12
    error_message = "The attacker reads two or three objects out of many; a bucket holding only the objects that get read removes the analyst's job of working out which ones mattered."
  }
}

run "object_keys_are_dated_and_sortable" {
  command = plan

  assert {
    condition = alltrue([
      for key in keys(local.exports) :
      can(regex("^exports/[0-9]{4}/[0-9]{2}/cost-allocation-[0-9]{4}-[0-9]{2}\\.csv$", key))
    ])
    error_message = "These keys are read aloud during the demo; a dated hierarchy is what makes 'they took July and August' a sentence rather than a lookup."
  }
}

run "the_bucket_is_never_public" {
  command = plan

  assert {
    condition = alltrue([
      aws_s3_bucket_public_access_block.exports.block_public_acls,
      aws_s3_bucket_public_access_block.exports.block_public_policy,
      aws_s3_bucket_public_access_block.exports.ignore_public_acls,
      aws_s3_bucket_public_access_block.exports.restrict_public_buckets,
    ])
    error_message = "This bucket is screen-shared while holding invented finance data; a demo that leaks its own props is not one to show a security team."
  }
}

run "the_bucket_can_be_torn_down_unattended" {
  command = plan

  assert {
    condition     = aws_s3_bucket.exports.force_destroy
    error_message = "Teardown must return the account to baseline without a human emptying a bucket by hand; everything in here is regenerated by the next apply."
  }
}
